# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParselSorgu
                                 A QGIS plugin
 TKGM Parsel Sorgu
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-10
        copyright            : (C) 2022 by Turker Gurcan
        email                : turker.gurcan@yandex.com.tr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParselSorgu class from file ParselSorgu.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ParselSorguV2 import ParselSorgu
    return ParselSorgu(iface)
