# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParselSorguDockWidget
                                 A QGIS plugin
 TKGM Parsel Sorgu
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-10
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Turker Gurcan
        email                : turker.gurcan@yandex.com.tr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtWidgets 
from qgis.PyQt import uic
from qgis.PyQt.QtCore import pyqtSignal
from .services import Services
from qgis.core import QgsVectorLayer, QgsProject
import qgis.core
import json


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ParselSorguV2_dockwidget_base.ui'))

class ParselSorguDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(ParselSorguDockWidget, self).__init__(parent)

        self.setupUi(self)
        self.service=Services()
        self.iller()
        self.btnAra.clicked.connect(self.iller)
        self.cbIller.currentIndexChanged.connect(self.ilceler)
        self.cbIlceler.currentIndexChanged.connect(self.mahalleler)
        self.btnAra.clicked.connect(self.parsel)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()


    def layerAdd(self,lyr,lyrGroup,lyrSubGroup,lyrName):
        QgsProject.instance().addMapLayer(lyr,False)

        lyRoot = QgsProject().instance().layerTreeRoot()

        group = lyRoot.findGroup(lyrGroup)
        subGroup = lyRoot.findGroup(lyrSubGroup)
        if group==None:

            group=lyRoot.insertGroup(0,lyrGroup)
            subGroup = group.addGroup(lyrSubGroup)
            subGroup.addLayer(lyr)
        else:

            if subGroup==None:
                subGroup = group.addGroup(lyrSubGroup)
                subGroup.addLayer(lyr)
            
            else:
                subGroup.addLayer(lyr)

        lyr.setName(lyrName)

    def iller(self):
        response = self.service.getData(0,region='il') 
        illiste = response.json()
        for il in illiste['features']:
            self.cbIller.addItem(il['properties']['text'], userData=il['properties']['id'])

    def ilceler(self):
        self.cbIlceler.clear()
        
        response = self.service.getData(self.cbIller.currentData(), region='ilce')
        ilceListe = response.json()
        for ilce in ilceListe['features']:
            self.cbIlceler.addItem(ilce['properties']['text'], userData=ilce['properties']['id'])

    def mahalleler(self):
        self.cbMahalleler.clear()
        ilce_id = self.cbIlceler.currentData()
        response = self.service.getData(ilce_id, region='mahalle')
        try:
            mahalleListe = response.json()
            for mahalle in mahalleListe['features']:
                self.cbMahalleler.addItem(mahalle['properties']['text'], userData=mahalle['properties']['id'])
        except:
            pass

    def parsel(self):
        Ada = self.txtAda.text()
        Parsel = self.txtParsel.text()
        mahid = self.cbMahalleler.currentData()
        response = self.service.getParsel(mahid ,Ada=Ada, Parsel=Parsel)
        json_object=json.dumps(response.json())
        ilceAd = self.cbIlceler.currentText()
        mahalleAd = self.cbMahalleler.currentText()
        layerName = "{0}/{1}".format(Ada, Parsel)
        layer = QgsVectorLayer(json_object, layerName, "ogr")
        self.layerAdd(layer,ilceAd,mahalleAd,layerName)
        


